# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://duxinfeng.github.io/example
title: 新风作浪
email: duxinfeng99@gmail.com
description: "I'm an iOS developer based in Beijing."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/iduxinfeng
  - title: github
    url: https://github.com/duxinfeng
  - title: linkedin
    url: https://weibo.com/duxinfeng

analytics :
    provider : google 
    google : 
        tracking_id : ''
